CMSEcommerce/Models/ErrorViewModel.cs
namespace CMSEcommerce.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CMSEcommerce/Models/Page.cs
using System.ComponentModel.DataAnnotations;

namespace CMSEcommerce.Models
{
    public class Page
    {
        public int Id { get; set; }
        [Required, MinLength(3 , ErrorMessage ="Minimum lenght is 3")]
        public string Title { get; set; }
        public string Slug { get; set; }
        [Required, MinLength(10, ErrorMessage = "Minimum lenght is 10")]
        public string Body { get; set; }
    }
}

CMSEcommerce/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace CMSEcommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CMSEcommerce/Areas/Admin/Controllers/PagesController.cs
using CMSEcommerce.infrastrectur;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

namespace CMSEcommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PagesController(datacontext context) : Controller
    {
        private readonly datacontext _context = context;
        public async Task<IActionResult> Index()
        {
            //slug= slug.IsNullOrEmpty()? "home" : slug;
            List<Page> Pages = await _context.Pages.ToListAsync();

            return View(Pages);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Page page)
        {
            if (ModelState.IsValid)
            {
                page.Slug = page.Title.ToLower().Replace(" ", "-");
                var Slug = await _context.Pages.FirstOrDefaultAsync(x => x.Slug == page.Slug);

                if (Slug != null)
                {
                    ModelState.AddModelError("", "That page already exiseta!");
                    return View(page);
                }
                _context.Add(page);
                await _context.SaveChangesAsync();
                TempData["Success"] = "The page has been added!";
                return RedirectToAction("Index");
            }

            return View(page);
        }

        public async Task<IActionResult> Edit(int id)
        {
            Page page = await _context.Pages.FindAsync(id);
            if (page == null)
            {
                return NotFound();
            }
            return View(page);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Page page)
        {
            if (ModelState.IsValid)
            {
                page.Slug = page.Id == 1 ? "home" : page.Title.ToLower().Replace(" ", "-");
                var Slug = await _context.Pages.FirstOrDefaultAsync(x => x.Slug == page.Slug && x.Id != page.Id);

                if (Slug != null)
                {
                    ModelState.AddModelError("", "That page already exiseta!");
                    return View(page);
                }
                _context.Update(page);
                await _context.SaveChangesAsync();
                TempData["Success"] = "The page has been edited!";
                return RedirectToAction("Index");
            }

            return View(page);
        }
        public async Task<IActionResult> Delete(int id)
        {
            Page page = await _context.Pages.FindAsync(id);
            if (page == null || id==1)
            {
                TempData["Error"] = "The page does not exist!";
            }
            else
            {
                _context.Pages.Remove(page);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }

    }
}

CMSEcommerce/Controllers/HomeController.cs
using CMSEcommerce.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CMSEcommerce.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CMSEcommerce/Controllers/PagesController.cs
using CMSEcommerce.infrastrectur;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

namespace CMSEcommerce.Controllers
{
    public class PagesController (datacontext context) : Controller
    {
        private readonly datacontext _context= context;
        public  async Task< IActionResult> Index(string slug = "")
        {
            slug= slug.IsNullOrEmpty()? "home" : slug;
            Page Page = await _context.Pages.Where(x=>x.Slug==slug).FirstOrDefaultAsync();
            if(Page == null) { return NotFound(); }
            return View(Page);
        }
    }
}

CMSEcommerce/infrastrectur/components/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CMSEcommerce.infrastrectur.components
{
    public class MenuViewComponent(datacontext context) : ViewComponent
    {
        private readonly datacontext _context = context;
        

        public async Task<IViewComponentResult> InvokeAsync() {
             return View(await _context.Pages.Where(x=>x.Slug != "home").ToListAsync());
        } 
    }
}

CMSEcommerce/Areas/Admin/Views/Dashboard/Index.cshtml
<h1>Dashboard</h1>

CMSEcommerce/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CMSEcommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CMSEcommerce.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" href="/" target="_blank">CMSEcommerce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a  asp-area="Admin"  asp-controller="Dashboard" asp-action="Index" class="nav-link text-dark">
                                Dashboard
                            </a>

                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Pages" asp-action="Index" class="nav-link text-dark">
                                Pages
                            </a>

                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_NotificationsPartial" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            ALLOUN - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CMSEcommerce/Areas/Admin/Views/Shared/components/Menu/Default.cshtml
@model IEnumerable<Page>

@foreach (var item in Model)
{
    <li class="nav-item">
        <a class =" nav-link text-dark" href="@item.Slug">@item.Title</a>

    </li>
}

CMSEcommerce/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CMSEcommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CMSEcommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CMSEcommerce.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CMSEcommerce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*await Component.InvokeAsync("Menu")*@
                        <vc:menu/>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CMSEcommerce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CMSEcommerce/Views/Shared/_NotificationsPartial.cshtml
@if(TempData["success"] != null)
{
    <div class="alert alert-success">
        @TempData["success"]
    </div>
}

@if (TempData["error"] != null)
{
    <div class="alert alert-danger">
        @TempData["error"]
    </div>
}